#!/bin/sh

set -e

rc=0
RULES_SAVE='/etc/iptables/sets'

load_rules()
{
	if [ ! -f $RULES_SAVE ]; then
		echo "Warning: skipping IPSET (no rules to load)"
	else
		ipset -exist restore < $RULES_SAVE 2>/dev/null
		if [ $? -ne 0 ]; then
			rc=1
		fi
	fi
}

ipset_save() {
	ipset save $1
}

ipset_save_def() {
	ipset save $1 | while read a rest; do
		case "$a" in
		create)
			echo "$a $rest"
			;;
		esac
	done
}

save_rules() {
	if [ ! -f $RULES_SAVE ]; then
	        touch $RULES_SAVE
        	chmod 0640 $RULES_SAVE
	fi
	
	{
		case "$MANAGED_SETS" in
		"")
			ipset_save
			;;
		\*)
			ipset_save_def
			;;
		*)
			for s in $MANAGED_SETS; do
				proc=

				case "$s" in
				*\*)
					s=${s%*\*}
					proc='ipset_save_def'
					;;
				*)
					proc='ipset_save'
					;;
				esac

				eval "[ -z \"\$${s}_set\" ] && $proc \"$s\" && ${s}_set=1" || break
			done
			;;
		esac
	} > $RULES_SAVE

	if [ $? -ne 0 ]; then
		rc=1
	fi
}

flush_rules()
{
	case "$MANAGED_SETS" in
	""|\*)
		ipset flush
		;;
	*)
		for s in $MANAGED_SETS; do
			case "$s" in
			\**)
				ipset flush ${s%*\*}
				;;
			*)
				ipset_flush $1
				;;
			esac
		done
		;;
	esac
}

case "$1" in
start)
	load_rules
	;;
restart|reload|force-reload)
	flush_rules
	load_rules
	;;
save)
	save_rules
	;;
stop)
	flush_rules
	;;
flush)
	flush_rules
	;;
*)
    echo "Usage: $0 {start|restart|reload|force-reload|save|flush}" >&2
    exit 1
    ;;
esac

exit $rc
